development:
  adapter: postgresql
  encoding: unicode
  database: psychlopedia_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

test: &test
  adapter: postgresql
  encoding: unicode
  database: psychlopedia_test
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: psychlopedia_production
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

cucumber:
  <<: *test
